/**
 * AUTO-GENERATED by `npm run import-menu` — DO NOT EDIT BY HAND.
 * Source: incoming/menu.csv + incoming/images/
 * Every run rewrites this file wholesale.
 *
 * Generated: 2026-09-01T10:57:10.439Z
 * Items: 0
 */
import type { MenuItem } from "./data";

export const GENERATED_ITEMS: MenuItem[] = [];
